transform:
  outputs:
    dev:
      dbname: admin_database 
      host: thes_psql 
      pass: admin123 
      port: 5432 
      schema: dbt_source 
      threads: 10
      type: postgres
      user: admin_user
  target: dev
